### ISSUE TITLE
Docker検証 in Windows

### ISSUE THREAD

**Issue by mkonagaya** [CoopTechOrg/WebERP#13]
Windowsで問題なく動くか検証お願いします

おそらく権限で躓くかも。

**Comment by hosimiya7** [comment]
Docker検証しました。
確認よろしくお願いします。

wslとdockerのユーザー権限が違うため、コンテナ内のファイルの編集ができないため以下の3点を主に変更しています。
・UID,GIDの追加
・chmodでディレクトリの権限変更
・ルートディレクトリを /app に変更(M1も変更)
(ルートディレクトリを新しく作ることでchmodコマンドが使えるようにするため)
