### ISSUE TITLE
テスト予習

### ISSUE THREAD

**Issue by mkonagaya** [CoopTechOrg/WebERP#14]
### 概要
実際にコーディングは先だと思いますが、先に
- テストの書き方
- Unit、Featureの違い
など調べたり試しに触ってみてください

### 参考URL
https://readouble.com/laravel/8.x/ja/testing.html

**Comment by funa074** [comment]
承知しました。確認します。

**Comment by mkonagaya** [comment]
@Rywwwwwww 
特に問題なさそうならクローズお願いします
