### ISSUE TITLE
ログイン機能の実装

### ISSUE THREAD

**Issue by mkonagaya** [CoopTechOrg/WebERP#23]
Laravel8はわかりませんが、とりあえず認証機能を実装してください

ログイン成功・失敗が確認できたらOKです

#22 完了後に着手

**Comment by sakaguchi-0725** [comment]
jetstreamをインストールしているからか、php artisan migrateコマンドを実施したらログイン機能は実装できました。
特にファイルが追加されたりしないので、コマンドを叩けばOKっぽいのですがどうしたらよいですか？

jetstreamドキュメント
[](https://jetstream.laravel.com/2.x/features/authentication.html)

**Comment by mkonagaya** [comment]
あ、もうログインは実装済みか。。失礼しました、よさそうですね。閉じときます！
