### ISSUE TITLE
composeバージョン 3.8 -> 3.3

### ISSUE THREAD

**Issue by mkonagaya** [CoopTechOrg/WebERP#26]
### OverView

docker-composeのバージョンが3.3でも動くか、確認して欲しい

### Assign

Windows @hosimiya7 
Other than Windows @Zuzu0725

**Comment by sakaguchi-0725** [comment]
m1環境でver3.3でも動作することを確認しました！

**Comment by mkonagaya** [comment]
ありがとうございます！！

**Comment by hosimiya7** [comment]
windowsでも動きました！

**Comment by mkonagaya** [comment]
OKでっす！
