### ISSUE TITLE
見積業務のデザイン

### ISSUE THREAD

**Issue by mkonagaya** [CoopTechOrg/WebERP#33]
### 概要
見積業務のデザイン及びコーディングをお願いしたい。

### 作成対象ページ
- 一覧ページ
- CRUDページ
- 請求書レイアウト

### 設計
[設計](https://github.com/CoopTechOrg/WebERP/tree/main/docs/Specification/Estimate)

### ブランチ
- 共通部分 : `feature/#33-core`
- 見積一覧 : `feature/#33-index`
- CRUD画面 : `feature/#33-crud`
- 見積書作成を作る : `feature/#33-quotation`

`feature/#33-core` を先行して、それを派生させてください

**Comment by mkonagaya** [comment]
#52, #53, #54 作りました。
このissueはcoreのPRを以てクローズで良いかも

**Comment by hosimiya7** [comment]
こなさんの方で見てもらって共通部分問題なさそうだったらいったんクローズで大丈夫です
リンク先がまだできてないので、後々直す部分はありそうですが…

**Comment by mkonagaya** [comment]
coreはマージしたのでクローズします
